component: express
name: politicodds-v1
stage: prod

inputs:
  description: Politicodds API
  src:
    src: ./
    exclude:
      - src
      - test
  env:
    NODE_ENV: production
  region: eu-west-2
